CONSUMER_KEY = "jPkzfXzsiAKQHVUR5LwaRL6pa" #API key
CONSUMER_SECRET = "e7RldzjYC6G5aWa66Cat0sxf1cgKgF3dmlOCIjUTvVArbbNVGt" #API secret key
ACCESS_TOKEN = "2609261629-G4THyx01YUaHVCohHmW0HOjotEOXHbHoZcY6C5X" #Access token
ACCESS_TOKEN_SECRET = "nOtPNTPhgzoMP8OybnddniSRizjWkwnCvo9wEZ0Vmja4C" #Access token secret